-- Business actions generated by AI Operator
CREATE TABLE IF NOT EXISTS business_actions (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  category text,
  recommendation text,
  impact text,
  status text DEFAULT 'pending',
  auto_executable boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  executed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_business_actions_status ON business_actions(status);

